# Generated by Django 6.0 on 2025-12-17 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='model3d',
            options={'verbose_name': 'Modelo 3D', 'verbose_name_plural': 'Modelos 3D'},
        ),
        migrations.AlterField(
            model_name='model3d',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='modelos'),
        ),
    ]
