# Generated by Django 6.0 on 2025-12-15 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model3d',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='modelos/'),
        ),
    ]
