# Generated by Django 6.0 on 2026-01-28 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_alter_model3d_options_alter_model3d_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='model3d',
            name='image_url',
            field=models.URLField(blank=True, help_text='Pega aquí el link directo a una imagen (https://...jpg/png/webp).', null=True),
        ),
    ]
